[graph]
targets = []
all-features = false
no-default-features = false

[output]
feature-depth = 1

[advisories]
ignore = []

[licenses]
allow = [
  "MIT",
  "Apache-2.0",
  "Unicode-3.0",
  "Unicode-DFS-2016",
  "WTFPL",
  "BSL-1.0",
  "CC0-1.0",
  "BSD-3-Clause",
  "ISC",
  "Zlib",
  "BSD-2-Clause",
]
confidence-threshold = 0.8
exceptions = []

[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"
allow = []
deny = []
skip = [
  { crate = "sync_wrapper@0.1.2", reason = "tower has not upgraded to 1.0 yet" },
  { crate = "windows-sys@0.52.0", reason = "gix pulls in two separate versions" },
]
skip-tree = [
  { name = "matchers", reason = "tracing-subscriber's env-filter pulls in an ancient regex version" },
]

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
